# Generated by Django 2.2 on 2021-06-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='itemImages',
            field=models.ImageField(blank=True, upload_to='Upload_images/'),
        ),
        migrations.AlterField(
            model_name='junkremoval',
            name='itemImages',
            field=models.ImageField(blank=True, upload_to='Upload_images/'),
        ),
        migrations.AlterField(
            model_name='moving',
            name='itemImages',
            field=models.ImageField(blank=True, upload_to='Upload_images/'),
        ),
    ]
