# Generated by Django 2.2 on 2021-06-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210607_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='itemImages',
            field=models.FileField(blank=True, upload_to='Upload_images/'),
        ),
        migrations.AlterField(
            model_name='junkremoval',
            name='itemImages',
            field=models.FileField(blank=True, upload_to='Upload_images/'),
        ),
        migrations.AlterField(
            model_name='moving',
            name='itemImages',
            field=models.FileField(blank=True, upload_to='Upload_images/'),
        ),
    ]
